# Generated by Django 6.0.4 on 2026-04-26 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('omschrijving', models.TextField()),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
                ('aangemaakt_door', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('discipline_een', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_een', to='challenges.discipline')),
                ('discipline_twee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_twee', to='challenges.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeDeelname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('bezig', 'Bezig'), ('ingediend', 'Ingediend'), ('goedgekeurd', 'Goedgekeurd'), ('afgekeurd', 'Afgekeurd')], default='bezig', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('ingediend_op', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('deelnemer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('deelnemer', 'Deelnemer'), ('begeleider', 'Begeleider')], default='deelnemer', max_length=20)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.discipline')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
