# Generated by Django 6.0.4 on 2026-05-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiel',
            name='discipline',
        ),
        migrations.AddField(
            model_name='profiel',
            name='disciplines',
            field=models.ManyToManyField(blank=True, to='challenges.discipline'),
        ),
    ]
