# Generated by Django 6.0.4 on 2026-05-04 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_remove_profiel_discipline_profiel_disciplines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_link', models.URLField()),
                ('beschrijving', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('bezig', 'Bezig'), ('ingediend', 'Ingediend'), ('goedgekeurd', 'Goedgekeurd'), ('afgekeurd', 'Afgekeurd')], default='bezig', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('ingediend_op', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('deelnemer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
