# Generated by Django 6.0.4 on 2026-05-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_project_partner_alter_project_deelnemer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChallengeDeelname',
        ),
    ]
