# Generated by Django 6.0.4 on 2026-06-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_delete_challengedeelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='opmerking',
            field=models.TextField(blank=True, null=True),
        ),
    ]
