# Generated by Django 6.0.5 on 2026-06-02 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_delete_challengedeelname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='geblokkeerd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='uitgenodigde_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uitnodigingen', to=settings.AUTH_USER_MODEL),
        ),
    ]
