# Generated by Django 6.0.4 on 2026-06-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_project_geblokkeerd_project_uitgenodigde_partner'),
        ('challenges', '0006_project_opmerking'),
    ]

    operations = [
    ]
