# Generated by Django 6.0.4 on 2026-06-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_merge_20260606_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='opmerking',
        ),
        migrations.AddField(
            model_name='profiel',
            name='quote',
            field=models.CharField(blank=True, default='Fast workflow, short projects', max_length=150),
        ),
    ]
