# Generated by Django 6.0.5 on 2026-06-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_remove_project_opmerking_profiel_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='goedgekeurd_op',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
