# Generated by Codex on 2026-06-09

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_project_goedgekeurd_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='aangemaakt_op',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
