# Generated by Codex on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_project_aangemaakt_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='afbeelding',
            field=models.FileField(blank=True, null=True, upload_to='project_afbeeldingen/'),
        ),
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
